version: "3.8"
services:
  app :
    build: ./app
    volumes:
    - ./app/servidores:/app/servidores
    - ./app/resultados:/app/resultados
  db:
    build: ./database/
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
