# FROM python:3.13.3
FROM python:3.10.12

WORKDIR /app

COPY web/ .

# COPY .env .

# RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# CMD [ "flask", "run", "--host=0.0.0.0" ]
